repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: debug-statements

-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        name: isort (python)

-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    -   id: black

-   repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        additional_dependencies: [flake8-bugbear, flake8-comprehensions]

-   repo: https://github.com/pycqa/pylint
    rev: v3.3.4
    hooks:
    -   id: pylint
        args: [--rcfile=.pylintrc]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.3.0
    hooks:
    -   id: mypy
        additional_dependencies: [types-requests, types-PyYAML]

# Custom hook to check for direct service instantiation in constructors
-   repo: local
    hooks:
    -   id: check-direct-instantiation
        name: Check for direct service instantiation
        entry: python scripts/check_di_compliance.py
        language: python
        types: [python]
        pass_filenames: true